version: "2.0"
services:
  splash:
    image: scrapinghub/splash
    ports:
      - "8050:8050"
  haipproxy:
    build: .
    command: sh run.sh
    volumes:
      - .:/haipproxy
    ports:
      - "3128:3128"
    links:
      - redis
      - splash
